DROP DATABASE IF EXISTS pawsome_DB;

CREATE DATABASE pawsome_DB;

USE pawsome_DB;

CREATE TABLE products (
  id INT (10) NOT NULL AUTO_INCREMENT,
  ITEM_ID VARCHAR(100) NULL,
  ITEM_NAME VARCHAR(45) NULL,
  ITEM_DESCRIPTION VARCHAR(300) NULL,
  CATEGORY VARCHAR(200) NULL,
  PRICE DECIMAL(10,2)NULL,
  STOCK_QUANTITY INT NULL,
  IMAGE_NAME LONGBLOB NOT NULL,
  PRIMARY KEY (id)
);


INSERT INTO products (ITEM_ID, ITEM_NAME, ITEM_DESCRIPTION, CATEGORY, PRICE,STOCK_QUANTITY,IMAGE_NAME)
VALUES("DA01", "YUMMY CHUMMIES","Wild alaska salmon with tender sweet potatoes exclusively from alaska","DOG TREATS", 2.99, 20, " " );

CREATE TABLE user_login (
  MEMBER_ID VARCHAR(45) NULL,
  FIRST_NAME VARCHAR(300) NULL,
  LAST_NAME VARCHAR(300) NULL,
  USER_NAME VARCHAR(300) NULL,
  USER_PASSWORD VARCHAR(300) NULL,
  UNIQUE KEY (MEMBER_ID)
);

CREATE TABLE orders (
  id INT (10) NOT NULL AUTO_INCREMENT,
  ORDER_ID VARCHAR(45) NULL,
  USER_ID VARCHAR(45) NULL,
  ITEM_ID VARCHAR(300) NULL,
  QUANITY INT NULL,
  PRICEPERITEM DECIMAL(10,3) NULL,
  TOTAL DECIMAL(10,3) NULL,
  PRIMARY KEY (id)
);

FOREIGN KEY (USER_ID) REFERENCES user_login(MEMBER_ID);

ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root'
