DDROP DATABASE IF EXISTS bamazon_DB;

CREATE DATABASE bamazon_DB;

USE bamazon_DB;

CREATE TABLE products (
  id INT (10) NOT NULL AUTO_INCREMENT,
  ITEM_NAME VARCHAR(45) NULL,
  ITEM_DESCRIPTION VARCHAR(300) NULL,
  ITEM_MADEWITH VARCHAR(200) NULL
  ITEM_INFO VARCHAR(200) NULL,
  WEIGHT IN LB DECIMAL(10,2)NULL,
  MSRP DECIMAL(10,3) NULL,
  OUR COST DECIMAL(10,3) NULL,
  SIZE DECIMAL(3,2) NULL,
  LENGTH DECIMAL(10,3) NULL,
  WIDTH DECIMAL(10,3) NULL,
  HEITH DECIMAL(10,3) NULL,
  STOCK_QUANTITY INT NULL,
  PRIMARY KEY (id)
);

INSERT INTO products (ITEM_NAME, ITEM_DESCRIPTION, ITEM_MADEWITH, ITEM_INFO, WEIGHT IN LB, MSRP, OUR COST,SIZE,LENGTH, WIDTH, HEIGHT)
VALUES ("DOG TREATS", "YUMMY CHUMMIES GRAIN FREE WILD ALASKA DOG TREATS","Wild alaska salmon with tender sweet potatoes exclusively from alaska","Made in the usa", 1.3, 13.59, 8.16, 14, 0, 0, 0 );



-- ### Alternative way to insert more than one row
-- INSERT INTO products (flavor, price, quantity)
-- VALUES ("vanilla", 2.50, 100), ("chocolate", 3.10, 120), ("strawberry", 3.25, 75);
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root'
